language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests
env:
  - ENV_STAGE=test
cache: pip
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b5b01da7487a990f966f
